packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  tailwindcss: ^3.4.4
  next: "14.2.5"
  "@tanstack/react-query": ^5.50.1
  "@trpc/server": 11.0.0-rc.446
  "@trpc/client": 11.0.0-rc.446
  "@trpc/react-query": 11.0.0-rc.446
  "@types/node": ^20.12.10

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
